In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load
housing_price_data_path = Path(r"C:\Users\gurpa\Documents\GitHub\project-1-group-3\MLS_Gurpal.csv")

# Read Housing Data and store into Panda DataFrames
housing_price_data_df = pd.read_csv(housing_price_data_path)

#Show DataFrame
housing_price_data_df.head()

,Location,CompIndex,CompBenchmark,CompYoYChange,SFDetachIndex,SFDetachBenchmark,SFDetachYoYChange,SFAttachIndex,SFAttachBenchmark,SFAttachYoYChange,THouseIndex,THouseBenchmark,THouseYoYChange,ApartIndex,ApartBenchmark,ApartYoYChange,Date
0,Adjala-Tosorontio,143.7,510000.0,12.00,143.7,510000.0,12.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-07-01
1,Adjala-Tosorontio,140.8,499700.0,13.82,140.8,499700.0,13.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01
2,Adjala-Tosorontio,142.7,506400.0,15.83,142.7,506400.0,15.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-09-01
3,Adjala-Tosorontio,138.4,491100.0,11.08,138.4,491100.0,11.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-10-01
4,Adjala-Tosorontio,145.4,516000.0,16.51,145.4,516000.0,16.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-01

In [2]:
#Adding district column and deleting columns that are not required for the analysis
housing_price_data_df = housing_price_data_df[["Location", 
                                               "CompIndex", 
                                               "CompBenchmark", 
                                               "CompYoYChange",
                                               "Date"]]

housing_price_data_df["District"] = ""

#Display new dataframe
housing_price_data_df.head()

,Location,CompIndex,CompBenchmark,CompYoYChange,Date,District
0,Adjala-Tosorontio,143.7,510000.0,12.00,2015-07-01,
1,Adjala-Tosorontio,140.8,499700.0,13.82,2015-08-01,
2,Adjala-Tosorontio,142.7,506400.0,15.83,2015-09-01,
3,Adjala-Tosorontio,138.4,491100.0,11.08,2015-10-01,
4,Adjala-Tosorontio,145.4,516000.0,16.51,2015-11-01,

In [3]:
#Filter out locations to Toronto specific locations only
housing_price_toronto = housing_price_data_df[(housing_price_data_df["Location"] == "City of Toronto") |
                                          (housing_price_data_df["Location"] == "Toronto C01") |
                                          (housing_price_data_df["Location"] == "Toronto C02") |
                                          (housing_price_data_df["Location"] == "Toronto C03") | 
                                          (housing_price_data_df["Location"] == "Toronto C04") |
                                          (housing_price_data_df["Location"] == "Toronto C05") | 
                                          (housing_price_data_df["Location"] == "Toronto C06") | 
                                          (housing_price_data_df["Location"] == "Toronto C07") |
                                          (housing_price_data_df["Location"] == "Toronto C08") |
                                          (housing_price_data_df["Location"] == "Toronto C09") |
                                          (housing_price_data_df["Location"] == "Toronto C10") |
                                          (housing_price_data_df["Location"] == "Toronto C11") |
                                          (housing_price_data_df["Location"] == "Toronto C12") |
                                          (housing_price_data_df["Location"] == "Toronto C13") |
                                          (housing_price_data_df["Location"] == "Toronto C14") |
                                          (housing_price_data_df["Location"] == "Toronto C15") |
                                          (housing_price_data_df["Location"] == "Toronto E01") |
                                          (housing_price_data_df["Location"] == "Toronto E02") |
                                          (housing_price_data_df["Location"] == "Toronto E03") |
                                          (housing_price_data_df["Location"] == "Toronto E04") |
                                          (housing_price_data_df["Location"] == "Toronto E05") |
                                          (housing_price_data_df["Location"] == "Toronto E06") |
                                          (housing_price_data_df["Location"] == "Toronto E07") |
                                          (housing_price_data_df["Location"] == "Toronto E08") |
                                          (housing_price_data_df["Location"] == "Toronto E09") |
                                          (housing_price_data_df["Location"] == "Toronto E10") |
                                          (housing_price_data_df["Location"] == "Toronto E11") |
                                          (housing_price_data_df["Location"] == "Toronto W01") |
                                          (housing_price_data_df["Location"] == "Toronto W02") |
                                          (housing_price_data_df["Location"] == "Toronto W03") |
                                          (housing_price_data_df["Location"] == "Toronto W04") |
                                          (housing_price_data_df["Location"] == "Toronto W05") |
                                          (housing_price_data_df["Location"] == "Toronto W06") |
                                          (housing_price_data_df["Location"] == "Toronto W07") |
                                          (housing_price_data_df["Location"] == "Toronto W08") |
                                          (housing_price_data_df["Location"] == "Toronto W09") |
                                          (housing_price_data_df["Location"] == "Toronto W10") 
                                         ]

#Create DataFrame
housing_price_toronto = pd.DataFrame(housing_price_toronto)

    

#Display Dataframe
housing_price_toronto

,Location,CompIndex,CompBenchmark,CompYoYChange,Date,District
567,City of Toronto,183.6,602000.0,6.93,2015-07-01,
568,City of Toronto,184.0,602000.0,6.93,2015-07-01,
569,City of Toronto,184.1,603600.0,7.54,2015-08-01,
570,City of Toronto,184.0,603600.0,7.54,2015-08-01,
571,City of Toronto,185.3,607600.0,8.62,2015-09-01,
...,...,...,...,...,...,...
4741,Toronto W10,312.8,710400.0,13.33,2020-11-01,
4742,Toronto W10,311.3,707000.0,13.45,2020-12-01,
4743,Toronto W10,312.8,710400.0,12.36,2021-01-01,
4744,Toronto W10,327.4,743500.0,12.62,2021-02-01,
4745,Toronto W10,340.0,772100.0,13.79,2021-03-01,

In [16]:
#Assign each Location to a District

#City of Toronto
housing_price_toronto.loc[(housing_price_toronto.Location == "City of Toronto"),['District']] = "Old Toronto"

#Toronto Central
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C01"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C02"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C03"),['District']] = "York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C04"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C06"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C07"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C08"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C09"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C10"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C11"),['District']] = "East York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C12"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C13"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C14"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto C15"),['District']] = "North York"

#Toronto Eastern
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E01"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E02"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E03"),['District']] = "East York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E04"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E05"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E06"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E07"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E08"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E09"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E10"),['District']] = "Scarborough"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto E11"),['District']] = "Scarborough"

#Toronto Western
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W01"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W02"),['District']] = "Old Toronto"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W03"),['District']] = "York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W04"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W05"),['District']] = "North York"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W06"),['District']] = "Etobicoke"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W07"),['District']] = "Etobicoke"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W08"),['District']] = "Etobicoke"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W09"),['District']] = "Etobicoke"
housing_price_toronto.loc[(housing_price_toronto.Location == "Toronto W10"),['District']] = "Etobicoke"

#Display DataFrame with new inputs under District
housing_price_toronto

,Location,CompIndex,CompBenchmark,CompYoYChange,Date,District
567,City of Toronto,183.6,602000.0,6.93,2015-07-01,Old Toronto
568,City of Toronto,184.0,602000.0,6.93,2015-07-01,Old Toronto
569,City of Toronto,184.1,603600.0,7.54,2015-08-01,Old Toronto
570,City of Toronto,184.0,603600.0,7.54,2015-08-01,Old Toronto
571,City of Toronto,185.3,607600.0,8.62,2015-09-01,Old Toronto
...,...,...,...,...,...,...
4741,Toronto W10,312.8,710400.0,13.33,2020-11-01,Etobicoke
4742,Toronto W10,311.3,707000.0,13.45,2020-12-01,Etobicoke
4743,Toronto W10,312.8,710400.0,12.36,2021-01-01,Etobicoke
4744,Toronto W10,327.4,743500.0,12.62,2021-02-01,Etobicoke
4745,Toronto W10,340.0,772100.0,13.79,2021-03-01,Etobicoke

In [17]:
#Export new DataFrame to CSV File for reference
housing_price_toronto.to_csv(r"C:\Users\gurpa\Documents\GitHub\project-1-group-3\Toronto_Districts_Gurpal_1.csv")